import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/(Navbar)/Navbar";
import { IntroProvider } from "./context/IntroContext";
import { SpeedInsights } from "@vercel/speed-insights/next"

const satoshi = localFont({
  src: [
    { path: "../public/fonts/Satoshi-Light.woff2",       weight: "300", style: "normal" },
    { path: "../public/fonts/Satoshi-Italic.woff2",      weight: "400", style: "italic" },
    { path: "../public/fonts/Satoshi-Bold.woff2",        weight: "700", style: "normal" },
    { path: "../public/fonts/Satoshi-BoldItalic.woff2",  weight: "700", style: "italic" },
    { path: "../public/fonts/Satoshi-Black.woff2",       weight: "900", style: "normal" },
    { path: "../public/fonts/Satoshi-BlackItalic.woff2", weight: "900", style: "italic" },
  ],
  variable: "--font-satoshi",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${satoshi.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
          <IntroProvider>
            <Navbar />
            {children}
            <SpeedInsights />
          </IntroProvider>
        </body>
    </html>
  );
}
